# Generated by Django 6.0.2 on 2026-03-01 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอพิจารณา'), ('approved', 'อนุมัติ'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('doc_type', models.CharField(choices=[('transcript', 'ใบแสดงผลการเรียน'), ('recommendation', 'หนังสือแนะนำ'), ('other', 'อื่นๆ')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scholarships.application')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('general', 'ทุนการศึกษาทั่วไป'), ('exchange', 'ทุนการศึกษาแลกเปลี่ยน'), ('fee_waiver', 'ทุนยกเว้นค่าธรรมเนียม'), ('lunch', 'ทุนอาหารกลางวัน')], max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('amount_per_semester', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'เปิดรับสมัคร'), ('closed', 'ปิดรับสมัคร'), ('draft', 'ฉบับร่าง')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarship'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('faculty', models.CharField(choices=[('computing', 'วิทยาลัยการคอมพิวเตอร์'), ('engineering', 'วิศวกรรมศาสตร์'), ('science', 'วิทยาศาสตร์'), ('management', 'การจัดการ'), ('other', 'อื่นๆ')], max_length=100)),
                ('major', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('gpax', models.FloatField(default=0.0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'scholarship')},
        ),
    ]
